// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pa.Backend.Dal;

#nullable disable

namespace Pa.Backend.Migrations
{
    [DbContext(typeof(PaContext))]
    [Migration("20231202080649_addSessionPathNullable")]
    partial class addSessionPathNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pa.Backend.Models.ImageDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dt_created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("file_name")
                        .HasColumnType("text");

                    b.Property<bool>("is_analyzed")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lst_modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("session_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Pa.Backend.Models.MetricDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("healthy_percent")
                        .HasColumnType("real");

                    b.Property<Guid>("image_id")
                        .HasColumnType("uuid");

                    b.Property<int>("index_type")
                        .HasColumnType("integer");

                    b.Property<float>("unhealthy_percent")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Pa.Backend.Models.SessionDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dt_created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("healthy_percent")
                        .HasColumnType("real");

                    b.Property<DateTime>("lst_modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("number_of_images")
                        .HasColumnType("integer");

                    b.Property<string>("session_name")
                        .HasColumnType("text");

                    b.Property<string>("session_path")
                        .HasColumnType("text");

                    b.Property<float>("unhealthy_percent")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
