// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pa.Backend.Dal;

#nullable disable

namespace Pa.Backend.Migrations
{
    [DbContext(typeof(PaContext))]
    [Migration("20231126165024_ChangeDbModel")]
    partial class ChangeDbModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pa.Backend.Models.ImageDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dtCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("fileName")
                        .HasColumnType("text");

                    b.Property<float>("healthyPercentage")
                        .HasColumnType("real");

                    b.Property<DateTime>("lstModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("session_id")
                        .HasColumnType("uuid");

                    b.Property<float>("unhealthyPercentage")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Pa.Backend.Models.SessionDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dtCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("healthyPercentage")
                        .HasColumnType("real");

                    b.Property<DateTime>("lstModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sessionName")
                        .HasColumnType("text");

                    b.Property<float>("unhealthyPercentage")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
